function htmlTagRevision(a,b,e){var d=a;if(""!=d&&(DEXTTOP.DEXT5.browser.ie&&11>=DEXTTOP.DEXT5.browser.ieVersion||DEXTTOP.DEXT5.browser.gecko))try{var c=d.toLowerCase().indexOf("<body"),g=d.toLowerCase().lastIndexOf("<body");if(-1<c&&-1<g&&c!=g)return a;if("ieplugin"!=DEXTTOP.G_CURREDITOR._config.runtimes&&-1<d.indexOf("mso-fareast-font-family")){var f=RegExp("<[^>]+style=(.*?)>","gi"),h="",c=!1;try{var k=d.match(f);if(k){for(var l=k.length,f=0;f<l;f++)d=d.replace(k[f],"_DEXT_T_S{"+f+"}_");for(f=
0;f<l;f++){var m=k[f];-1<m.indexOf("-font-family")&&(m=m.replace("-font-family","-font-dext-family"));g=!1;0>m.indexOf("font-family")&&(g=!0);-1<m.indexOf("-font-dext-family")&&(m=m.replace("-font-dext-family","-font-family"));g&&(m=m.replace(/mso-fareast-font-family/gi,"font-family"));d=d.replace("_DEXT_T_S{"+f+"}_",m)}}}catch(n){c=!0}c&&(d=a)}b&&(d=DEXT5_EDITOR.HTMLParser.RemoveOfficeTag(d,e));var h=d.toLowerCase(),p=realValue2=d,q=h.lastIndexOf("<body"),r=h.indexOf("</body");if(-1<q&&-1<r)try{var t=
p.substring(r),u=p.substring(q).indexOf(">"),v=p.substring(0,q+u+1),d=p.substring(q+u+1,r)}catch(w){q=r=-1,d=realValue2}realValue2=null;d=DEXT5_EDITOR.HTMLParser.HTMLtoXML(d,e);-1<q&&-1<r&&(d=v+d+t)}catch(x){return a}else if("1"==DEXTTOP.G_CURREDITOR._config.removeComment)for(b=d.indexOf("\x3c!--"),a=d.indexOf("--\x3e");-1<b&&-1<a;)b=d.substring(0,b),d=d.substring(a+3),d=b+d,b=d.indexOf("\x3c!--"),a=d.indexOf("--\x3e");else d=d.replace(/--\x3e\s</gi,"--\x3e<");return d}var G_wordProcessorType="";
function SetCorrectOfficeHtml(a){var b=a;if(-1<a.indexOf("<meta name=ProgId content=Word.Document>")||-1<a.indexOf('<meta name=Generator content="Microsoft Word'))G_wordProcessorType="DOC",a=GetMsWordHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=Excel.Sheet>"))G_wordProcessorType="XLS",a=GetMsExcelHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=PowerPoint.Slide>"))G_wordProcessorType="PPT",a=GetMsPptHtml2(a);else if(-1<a.indexOf('<meta name=Generator content="Jungum Global">'))G_wordProcessorType=
"GUL",a=GetJungumHtml(a);else if(isHwpPasteAction(a))G_wordProcessorType="HWP",a=GetHanHwpHtml(a);else if(-1<a.indexOf(' xmlns:m="http://schemas.microsoft.com/office/'))G_wordProcessorType="PPT",a=GetMsPptHtml2(a);else if(-1<a.indexOf('<meta name=Generator content="Microsoft'))G_wordProcessorType="DOC",a=GetMsWordHtml(a);else if(!DEXTTOP.DEXT5.browser.ie){var b=a.indexOf("\x3c!--StartFragment--\x3e"),e=a.lastIndexOf("\x3c!--EndFragment--\x3e");-1<b&&-1<e&&(b=a.substr(b+20),e=b.lastIndexOf("\x3c!--EndFragment--\x3e"),
-1<e&&(a=b=b.substring(0,e)))}a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !supportEmptyParas]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[if !supportEmptyParas]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[if !supportLists]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[endif]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");return a=DEXTTOP.DEXT5.util.replaceAll(a,
"<![if ppt]>","")}
function GetMsWordHtml(a){var b=a,e,b=a.indexOf("/* Style Definitions */"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+23),d=b.indexOf("</head>"),-1<d&&(e=b.substring(0,d),e=GetStyleMap(e)));var b=a,d=!1,c="\x3c!--StartFragment--\x3e",g="\x3c!--EndFragment--\x3e",f=a.indexOf(c),h=a.indexOf(g);if(-1==f&&-1==h){var c="<body ",g="</body>",k=a.indexOf(c);-1<k&&(h=a.indexOf(">",k),c=a.Mid(k,h-k+1),f=a.indexOf(c),h=a.indexOf(g))}if(-1<f&&-1<h&&(b=a.substr(f+c.length),h=b.indexOf(g),-1<h)){for(;;)if(a=
b.indexOf(g,h+g.length),-1<a)h=a;else break;a=b=b.substring(0,h);d=!0}if(d){a=b;var l="<div class=WordSection1>",g=a.indexOf(l);-1==g&&(l='<div class="WordSection1">',g=a.indexOf(l));-1<g&&(l=DEXTTOP.DEXT5.util.replaceAll(a,l,""),l.length!=a.length&&(a=l,l=a.lastIndexOf("/"),-1<l&&(a=a.substring(0,l-1))));c="\x3c!--[if supportFields]>";for(g="<![endif]--\x3e";;){f=a.indexOf(c);-1<f&&(h=a.indexOf(g,f+c.length));l=a.length;if(f>l||h>l)break;if(-1<f&&-1<h){if(f<h){var m,b=a.substring(0,f);m=a.substr(h+
g.length);a=b+m}}else break;h=-1}}if(d){c="\x3c!--[if gte vml 1]>";g="<![if !vml]>";try{for(;;){f=a.indexOf(c);-1<f&&(h=a.indexOf(g,f+c.length));var n=a.length;if(n>f||n>h){a=DEXTTOP.DEXT5.util.replaceAll(a,c,"");a=DEXTTOP.DEXT5.util.replaceAll(a,g,"");break}if(-1<f&&-1<h)f>h?(b=a.substring(0,f),m=a.substr(f),b=DEXTTOP.DEXT5.util.replaceAll(b,g,""),a=b+m):(b=a.substring(0,f),m=a.substr(h+g.length),a=b+m,d=!0);else break}}catch(p){}}c="\x3c!--[if gte mso 9]>";g="<![endif]--\x3e";try{for(;;){f=a.indexOf(c);
-1<f&&(h=a.indexOf(g,f+c.length));l=a.length;if(f>l||h>l){a=DEXTTOP.DEXT5.util.replaceAll(a,c,"");a=DEXTTOP.DEXT5.util.replaceAll(a,g,"");break}if(-1<f&&-1<h)f>h?(b=a.substring(0,f),m=a.substr(f),b=DEXTTOP.DEXT5.util.replaceAll(b,g,"")):(b=a.substring(0,f),m=a.substr(h+g.length)),a=b+m;else break}}catch(q){}d&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"><![endif]></span>"," /></span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]></span>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>",
"</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !vml]>",""));a=RepaireSpanInImageTag4MsWord(a);a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:rect ","<div ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:rect>","</div>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shadow ","<hr ");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shape ","<span ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:shape>","</span>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:imagedata","<img border=0");a=DEXTTOP.DEXT5.util.replaceAll(a,
"<![if !supportLists]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");return a=setPasteClassStyle(e,a,!0)}
function GetMsExcelHtml(a){var b=a,e,b=a.indexOf("<style>"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+7),d=b.indexOf("</head>"),-1<d&&(e=b.substring(0,d),e=GetStyleMap(e)));var b=a,d=!1,c,g="</body>",f=a.indexOf("<table"),h=a.indexOf(g);-1<f&&-1<h&&(b=a.substr(f),h=b.indexOf(g),-1<h&&(b=b.substring(0,h),d=!0));if(d){d=!1;a=b;c="\x3c!--[if gte vml 1]>";g="<![if !vml]>";try{for(;;){f=a.indexOf(c);-1<f&&(h=a.indexOf(g,f+c.length));var k=a.length;if(k>f||k>h){a=DEXTTOP.DEXT5.util.replaceAll(a,
c,"");a=DEXTTOP.DEXT5.util.replaceAll(a,g,"");break}if(-1<f&&-1<h)if(f>h){var l,b=a.substring(0,f);l=a.substr(f);b=DEXTTOP.DEXT5.util.replaceAll(b,g,"");a=b+l}else b=a.substring(0,f),l=a.substr(h+g.length),a=b+l,d=!0;else break}}catch(m){}}d&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"></span><![endif]>"," /></span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),k=_T("<![if !vml]>"),a=DEXTTOP.DEXT5.util.replaceAll(a,k,""));a=DEXTTOP.DEXT5.util.replaceAll(a,
"<v:rect ","<div ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:rect>","</div>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shadow ","<hr ");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shape ","<span ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:shape>","</span>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:imagedata","<img border=0");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");k=a.indexOf("<col ");-1<k&&(a=a.substring(0,k)+"\n<colgroup>\n"+
a.substring(k,a.length+1));k=a.indexOf("<tr ");-1<k&&(a=a.substring(0,k)+"\n<tbody>\n"+a.substring(k,a.length+1),k=a.lastIndexOf("</table>"),-1<k&&(a=a.substring(0,k)+"\n</tbody>\n"+a.substring(k,a.length+1)));a=setPasteClassStyle(e,a);"1"==DEXTTOP.G_CURREDITOR._config.officeLineFix&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"border-left:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-top:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-right:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-bottom:none;",
""));a=DEXTTOP.DEXT5.util.replaceAll(a,"\r","");return a=DEXTTOP.DEXT5.util.replaceAll(a,"\n","")}
function GetMsPptHtml2(a){var b=a,e,b=a.indexOf("\x3c!--tr"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+6),d=b.indexOf("</head>"),-1<d&&(e=b.substring(0,d),e=GetStyleMap(e)));b=a.indexOf("\x3c!--StartFragment--\x3e");d=a.indexOf("\x3c!--EndFragment--\x3e");if(-1<b&&-1<d&&(b=a.substr(b+20),d=b.indexOf("\x3c!--EndFragment--\x3e"),-1<d)){for(;;)if(a=b.indexOf("\x3c!--EndFragment--\x3e",d+18),-1<a)d=a;else break;a=b=b.substring(0,d)}a=setPasteClassStyle(e,a);"1"==DEXTTOP.G_CURREDITOR._config.officeLineFix&&
(a=DEXTTOP.DEXT5.util.replaceAll(a,"border-right:none;",""));e=RegExp("<spanstyle","ig");a=a.replace(e,"<span style");return a=a.replace(e,"<p style")}
function GetJungumHtml(a){if("1"==DEXTTOP.G_CURREDITOR._config.useHtmlProcessByWorker)return a;var b=a.indexOf("<body>"),e=a.indexOf("</body>"),d=!1;-1<b&&-1<e&&(strTemp=a.substr(b+6),e=strTemp.indexOf("</body>"),-1<e&&(a=strTemp=strTemp.substring(0,e),d=!0));if(d){b=document.createElement("div");b.innerHTML=a;a=b.getElementsByTagName("table");for(var e=a.length,c,g,d=0;d<e;d++)""!=a[d].getAttribute("width")&&(c=parseInt(a[d].getAttribute("width"),10)),""!=a[d].getAttribute("height")&&(g=parseInt(a[d].getAttribute("height"),
10)),c&&(a[d].style.width=c+"px"),g&&(a[d].style.height=g+"px");a=b.innerHTML}return a}
function GetHanHwpHtml(a){var b=a,b=">\x3c!--p.0",e="</head>",d,c=a.indexOf(b),g=a.indexOf(e);-1==c&&(b=">\r\n\x3c!--p.0",c=a.indexOf(b));-1==c&&(b="\x3c!--p.0",c=a.indexOf(b));-1==g&&(e="</HEAD>",g=a.indexOf(e));-1<c&&-1<g&&(b=a.substr(c+(b.length-3)),g=b.indexOf(e),-1<g&&(d=b.substring(0,g),d=GetStyleMap(d)));var b=a,f=!1,h="\x3c!--StartFragment--\x3e",e="\x3c!--EndFragment--\x3e",g=a.indexOf(h),c=a.indexOf(e);if(-1<g&&-1<c&&(b=a.substr(g+h.length),c=b.indexOf(e),-1<c)){for(;;)if(f=b.indexOf(e,
c+e.length),-1<f)c=f;else break;b=b.substring(0,c);f=!0}if(f){f=!1;a=b;h="\x3c!--[if gte vml 1]>";e="<![if !vml]>";try{for(;;){g=a.indexOf(h);-1<g&&(c=a.indexOf(e,g+h.length));var k=a.length;if(k>g||k>c){a=DEXTTOP.DEXT5.util.replaceAll(a,h,"");a=DEXTTOP.DEXT5.util.replaceAll(a,e,"");break}if(-1<g&&-1<c)if(g>c){var l,b=a.substring(0,g);l=a.substr(g);b=DEXTTOP.DEXT5.util.replaceAll(b,e,"");a=b+l}else b=a.substring(0,g),l=a.substr(c+e.length),a=b+l,f=!0;else break}}catch(m){}}a=setPasteClassStyle(d,
a);f&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"/><![endif]>"," />"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !vml]>",""));a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !supportEmptyParas]>&nbsp;<![endif]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"background:#ffffff;","");a=DEXTTOP.DEXT5.util.replaceAll(a,"mso-fareast-","");a=DEXTTOP.DEXT5.util.replaceAll(a,
"mso-hansi-","");a=DEXTTOP.DEXT5.util.replaceAll(a,"mso-ascii-","");a=DEXTTOP.DEXT5.util.replaceAll(a,"mso-bidi-","");return a=DEXTTOP.DEXT5.util.replaceAll(a,"mso-","")}
function GetStyleMap(a){var b={};a=a.split("}");for(var e="",d=a.length,c=0;c<d;c++){var g=a[c].split("{"),f=g.length;if(2==f)for(var h=0;h<f-1;h++){var k=g[h],l=g[h+1],k=k.replace(/\r\n/g,""),k=k.replace(/\r/g,""),k=k.replace(/\n/g,""),k=k.replace(/\t/g,""),l=l.replace(/\r\n/g,""),l=l.replace(/\r/g,""),l=l.replace(/\n/g,""),l=l.replace(/\t/g,"");""==e&&"td"==k&&(e=l=DEXTTOP.DEXT5.util.replaceAll(l,"'",'"'));0<k.length&&(l=DEXTTOP.DEXT5.util.replaceAll(l,"'",'"'),"."==k.substring(0,1)&&0<e.length?
b[k]=e+l:b[k]=l)}}return b}
function RepaireSpanInImageTag4MsWord(a){for(var b,e,d,c,g;;)if(b="<v:shape ",e=a.indexOf(b),-1==e&&(b="<v:shape\r\n",e=a.indexOf(b)),-1<e)if(d=a.indexOf("</v:shape>",e+b.length),c=a.indexOf("<v:imagedata",e+b.length),-1<d&&-1<c&&c<d)if(g=a.indexOf("/>",c+12),-1<g)c=a.substring(0,e),e=a.substr(e,g-e+2),a=a.substr(d+10),e=DEXTTOP.DEXT5.util.replaceAll(e,"<v:imagedata"," "),e=DEXTTOP.DEXT5.util.replaceAll(e,b,"<v:imagedata "),e=DEXTTOP.DEXT5.util.replaceAll(e,">"," "),e=DEXTTOP.DEXT5.util.rtrim(e),e+=
">",e=DEXTTOP.DEXT5.util.replaceAll(e,"/>"," />"),e=DEXTTOP.DEXT5.util.replaceAll(e,"  "," "),a=c+e+a;else break;else break;else break;return a}
function setPasteClassStyle(a,b,e){for(var d in a){var c=a[d],c=DEXTTOP.DEXT5.util.replaceAll(c,"hairline ","dotted "),c=DEXTTOP.DEXT5.util.replaceAll(c," hairline;"," dotted;"),c=DEXTTOP.DEXT5.util.replaceAll(c,"dot-dot-dash ","dotted "),c=DEXTTOP.DEXT5.util.replaceAll(c," dot-dot-dash;"," dotted;"),c=DEXTTOP.DEXT5.util.replaceAll(c,"dot-dash ","dotted "),c=DEXTTOP.DEXT5.util.replaceAll(c," dot-dash;"," dotted;"),c=DEXTTOP.DEXT5.util.replaceAll(c,"dot-dash-slanted ","dotted "),c=DEXTTOP.DEXT5.util.replaceAll(c,
" dot-dash-slanted;"," dotted;");d=d.split(",")[0];d=d.substring(d.indexOf("."));if("."==d.substring(0,1))for(var g=new RegExp("<[^>]*class=(\"|'|)"+d.substr(1)+"[\\s\\S]*?>","i"),f;f=g.exec(b);){var h=b.substring(0,f.index),k=f[0].toString();b=b.substr(f.index+f[0].length);f=/style=("|'|)/i;if(1==f.test(k)){var l=RegExp.$1;"'"==l?c=c.replace(/'/gi,'"'):'"'==l&&(c=c.replace(/"/gi,"'"));k=k.replace(f,"style="+l+c+" ");f=new RegExp("class=(\"|'|)"+d.substr(1)+"(\"|'|)","i");k=k.replace(f,"")}else f=
new RegExp("class=(\"|'|)"+d.substr(1)+"(\"|'|)","i"),k=k.replace(f,"style='"+c+"'");b=h+k+b}if(e&&(h=d.toLowerCase(),-1<h.indexOf("h1")||-1<h.indexOf("h2")||-1<h.indexOf("h3")||-1<h.indexOf("h4")||-1<h.indexOf("h5")||-1<h.indexOf("h6"))&&(c=GetFontSizeForWordH1ToH7Tag(c),""!=c))for(var g=new RegExp("<"+d+"[^>]*>","igm"),g=b.match(g),l=g.length,m=0;l>m;m++)h=b.substring(0,b.indexOf(g[m])),k=g[m],b=b.substring(b.indexOf(g[m])+g[m].length),f=/(style=("|'|))/i,1==f.test(k)?k=k.replace(f,RegExp.$1+c):
(f=new RegExp("<"+d,"i"),k=k.replace(f,"<"+d+" style='"+c+"'")),b=h+k+b}return b}function GetFontSizeForWordH1ToH7Tag(a){var b="",e=a.indexOf("font-size");-1<e&&(a=a.substr(e),e=a.indexOf(";"),-1<e&&(b=a.substring(0,e),b+=";"));return b}function isHwpPasteAction(a){return-1<a.indexOf(">\x3c!--p.")||-1<a.indexOf('<META NAME="Generator" CONTENT="Hancom HWP')||-1<a.indexOf("\x3c!--[if !supportEmptyParas]--\x3e")?!0:!1}
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.officeClean&&(DEXTTOP.DEXT5.util.officeClean=function(a,b){if(""==a||void 0==a)return"";var e=null,d=[];a=a.replace(/\.0px/g,"px");a=a.replace(/\t/g,"");a=DEXTTOP.DEXT5.util.removeOfficeDummyTag(a,"\x3c!--[if supportFields]>","<![endif]--\x3e");e=RegExp("<o:p></o:p>","gi");a=a.replace(e,"");e=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(e,"");e=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(e,"");e=RegExp("<o:p ([^>]+)>\\s+</o:p>",
"gi");a=a.replace(e,"");e=RegExp('<[^>]+(lang=["]?en-us["])[^>]*>',"gi");if(e=a.match(e))for(var d=e.length,c=0;c<d;c++){var g=e[c],f=RegExp('\\slang=[\\"]?en-us[\\"]?',"gi"),g=g.replace(f,"");a=a.replace(e[c],g)}e=RegExp("<[^>]+(mso)[^>]*>","gi");if(e=a.match(e))for(d=e.length,c=0;c<d;c++)g=e[c],"1"==DEXTTOP.G_CURREDITOR._config.removeMsoClass&&(f=RegExp('\\sclass=[\\"]?(mso)\\w+[\\"]?',"gi"),g=g.replace(f,"")),g=g.replace(/&quot;/gi,"^"),f=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;',
"gi"),g=g.replace(f,""),f=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;?',"gi"),g=g.replace(f,""),f=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?'\"\\^@%\\.\\\\_]+; ?","gi"),g=g.replace(f,""),f=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?]+(['\"])","gi"),g=g.replace(f,"$1"),g=g.replace(/\^/gi,"&quot;"),a=a.replace(e[c],g);a=DEXTTOP.DEXT5.util.replaceAll(a,"hairline","dotted");for(c=0;5>c;c++){d=["o:p","span","font"];f=d.length;for(g=0;g<f;g++)e=new RegExp("<"+d[g]+"[^>]*></"+d[g]+">","gi"),a=a.replace(e,
""),e=new RegExp("<"+d[g]+"[^>]*>&nbsp;</"+d[g]+">","gi"),a=a.replace(e,"&nbsp;"),"span"!=d[g]&&(e=new RegExp("<"+d[g]+"[^>]*> </"+d[g]+">","gi"),a=a.replace(e,"&nbsp;"));d=["o","v","w","m","x"];f=d.length;for(g=0;g<f;g++)0==g&&(a=a.replace(/<o:p/gi,"<dexto:p")),e=new RegExp("<"+d[g]+":[^/>]+/>","gi"),a=a.replace(e,""),e=new RegExp("<"+d[g]+":[^>]+>[^<]*</"+d[g]+":[^>]+>","gi"),a=a.replace(e,""),g==f-1&&(a=a.replace(/<dexto:p/gi,"<o:p"))}a=a.replace(/style=""/gi,"");a=a.replace(/style=''/gi,"");a=
a.replace(/\s>/gi,">");a=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(a);a=a.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");a=a.replace(/<\/td>&nbsp;<\/td>/g,"</td></td>");a=a.replace(/<\/th>&nbsp;<\/tr>/g,"</th></tr>");a=a.replace(/<\/th>&nbsp;<\/th>/g,"</th></th>");if(DEXTTOP.DEXT5.browser.ie&&10>DEXTTOP.DEXT5.browser.ieVersion){var e=a.length,g=d=!1,h=f="",k="";if(-1==a.indexOf("<")&&-1==a.indexOf(">"))for(c=0;c<e;c++)f=a.charAt(c),h=a.charAt(c+1)," "!=f&&32!=f.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||
(f="&nbsp;"),k+=f;else for(c=0;c<e;c++)f=a.charAt(c),h=a.charAt(c+1),"<"==f?(d=!1,g="p"==h.toLowerCase()?!0:!1):">"==f&&1==g?d=!0:1!=d||" "!=f&&32!=f.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(f="&nbsp;"),k+=f;a=k}0==b&&(a=DEXTTOP.DEXT5.util.removeLocalFileImage(a));return a});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.removeLocalFileImage&&(DEXTTOP.DEXT5.util.removeLocalFileImage=function(a){if(""==a||void 0==a)return"";a=a.replace(/file:\/\/\//gi,"dext_local_file_image");reg_exp=RegExp("<img[^>]+dext_local_file_image[^>]+>","gi");return a=a.replace(reg_exp,"")});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.removeOfficeDummyTag&&(DEXTTOP.DEXT5.util.removeOfficeDummyTag=function(a,b,e){var d=a;try{for(var c=a.indexOf(b),g=a.indexOf(e);-1<c&&-1<g;)var f=d.substring(0,c),h=d.substring(g+e.length),d=f+h,c=d.indexOf(b),g=d.indexOf(e)}catch(k){d=a}return d});"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.replaceAll&&(DEXTTOP.DEXT5.util.replaceAll=function(a,b,e){a&&""!=a&&(a=a.split(b).join(e));return a});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp&&(DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp=function(a){var b=a,e,d="";try{for(var c="span font a b strong i em strike u sup sub".split(" "),g=c.length,f=0;f<g;f++)for(var h=0;h<g;h++){d=b;e=new RegExp("<"+c[f]+" *([^>?+])*>(\\s+)</"+c[h]+">","gi");reg_exp2="u"==c[h]?new RegExp("</"+c[f]+">(\\s+)<"+c[h]+"[^l]","gi"):new RegExp("</"+c[f]+">(\\s+)<"+c[h]+" *([^>?+])*>","gi");reg_exp3=new RegExp("<"+c[f]+" *([^>?+])*>(\\s+)<"+
c[h]+">","gi");reg_exp4="u"==c[h]?new RegExp("</"+c[f]+">(\\s+)</"+c[h]+"[^l]","gi"):new RegExp("</"+c[f]+">(\\s+)</"+c[h]+" *([^>?+])*>","gi");try{var k=b.match(e);if(k)for(var l=k.length,m=0;m<l;m++)var n=k[m],p=/>\s+</.exec(n),q=p[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(p,q),b=b.replace(k[m],n);if(k=b.match(reg_exp2))for(l=k.length,m=0;m<l;m++)n=k[m],"b"==c[h]&&-1<match_string.toLowerCase().indexOf("<br")||(p=/>\s+</.exec(n),q=p[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),
n=n.replace(p,q),b=b.replace(k[m],n));if(k=b.match(reg_exp3))for(l=k.length,m=0;m<l;m++)n=k[m],"b"==c[f]&&-1<match_string.toLowerCase().indexOf("<br")||(p=/>\s+</.exec(n),q=p[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(p,q),b=b.replace(k[m],n));if(k=b.match(reg_exp4))for(l=k.length,m=0;m<l;m++)n=k[m],p=/>\s+</.exec(n),q=p[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(p,q),b=b.replace(k[m],n)}catch(r){b=d}}for(f=0;f<g;f++)for(h=0;h<g;h++)d="","b"==c[h]?d="[^r]":"u"==
c[h]&&(d="[^l]"),e=new RegExp("/"+c[f]+">\\s<"+c[h]+d,"gi"),b=b.replace(e,"/"+c[f]+">&nbsp;<"+c[h]),e=new RegExp("/"+c[f]+">\\s\\n<"+c[h]+d,"gi"),b=b.replace(e,"/"+c[f]+">&nbsp;<"+c[h])}catch(t){b=a}return b});"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.rtrim&&(DEXTTOP.DEXT5.util.rtrim=function(a){return""==a?a:a.replace(/\s+$/,"")});
