(function(){function n(a){var e={};a=a.split(",");for(var c=0;c<a.length;c++)e[a[c]]=!0;return e}var r=/^<([-A-Za-z0-9_]+)((?:\s+\w+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,v=/^<\/([-A-Za-z0-9_:@.]+)[^>]*>/,x=/([-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,t=/^<([-A-Za-z0-9_:-]+)((?:\s+[a-zA-Z_0-9:-]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,y=/([-A-Za-z0-9_:-]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,
z=n("colgroup,col"),A=n("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed");n("area,base,basefont,br,col,frame,img,input,isindex,link,meta,param,embed");var B=n("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,script,table,tbody,td,tfoot,th,thead,tr,ul,h1,h2,h3,h4,h5,h6,figure"),w=!1,l="a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var",
u=n(l),C=n("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),D=n("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),E=n("");"undefined"==typeof DEXT5_EDITOR&&(DEXT5_EDITOR={});DEXT5_EDITOR.HTMLParser=function(a,e,c){function g(a,b,d,e){b=b.toLowerCase();if(B[b]){for("table"!=k.last()&&"tbody"!=k.last()||"td"!=b||g("","tr","","");k.last()&&u[k.last()];)f("",k.last());"p"!=k.last()||"table"!=b&&"hr"!=b&&"center"!=b&&"figure"!=b||f("","p")}C[b]&&
k.last()==b&&f("",b);(e=A[b]||!!e)||k.push(b);if(c.start){var h=[];a=r.test(a)?x:y;d.replace(a,function(a,b,d,c,k){d=d?d:c?c:k?k:D[b]?b:"";c="";""!=a&&(a=a.substring(a.indexOf(b)+b.length),a=a.substring(a.indexOf("=")+1),a=a.replace(/^\s+/,""),c=a.substring(0,1),"'"!=c&&'"'!=c&&(c=""));h.push({name:b,value:d,escaped:d.replace(/(^|[^\\])"/g,'$1\\"'),quotationmark:c})});c.start&&c.start(b,h,e)}}function f(a,b){if(b)for(b=b.toLowerCase(),d=k.length-1;0<=d&&k[d]!=b;d--);else var d=0;if(0<=d){for(var e=
k.length-1;e>=d;e--)c.end&&c.end(k[e]);k.length=d}}var b,d,k=[],l=a;for(k.last=function(){return this[this.length-1]};a;){d=!0;if(k.last()&&E[k.last()])a=a.replace(new RegExp("(.*)</"+k.last()+"[^>]*>"),function(a,b){b=b.replace(/\x3c!--(.*?)--\x3e/g,"$1").replace(/<!\[CDATA\[(.*?)]]\x3e/g,"$1");c.chars&&c.chars(b);return""}),f("",k.last());else{var h=a.indexOf("<");b=a.indexOf(">")+1;var q=a.substring(h,b);if(0==a.indexOf("\x3c!--"))b=a.indexOf("--\x3e"),0<=b&&(c.comment&&c.comment(a.substring(4,
b)),a=a.substring(b+3),d=!1);else if(0==a.toLowerCase().indexOf("<?xml"))b=a.indexOf("/>"),0<=b&&(a=a.substring(b+2),d=!1);else if(0!=a.indexOf("<")&&"</"+k.last()+">"==q.replace(/ /ig,""))d=a.substring(0,h),a=a.substring(b),a=d+"</"+k.last()+">"+a,d=!0;else if(0==a.indexOf("</")){if(b=a.match(v))a=a.substring(b[0].length),b[0].replace(v,f),d=!1}else if(0==a.indexOf("<"))if(b=a.match(r))a=a.substring(b[0].length),b[0].replace(r,g),d=!1;else if(b=a.match(t))a=a.substring(b[0].length),b[0].replace(t,
g),d=!1;else{if("1"==DEXTTOP.G_CURREDITOR._config.removeIncorrectAttribute&&(b=a.indexOf("<"),q=a.indexOf(">"),0==b&&0<q)){var p=a.substring(0,q+1),m=h=b=0;0<p.indexOf('\ub9d1\uc740=""')?(b=p.indexOf('\ub9d1\uc740=""'),h=5,m=p.split('\ub9d1\uc740=""').length):0<p.indexOf("\ub9d1\uc740=''")&&(b=p.indexOf("\ub9d1\uc740=''"),h=5,m=p.split("\ub9d1\uc740=''").length);if(2==m&&0<b&&(q=a.substring(q+1),m=p.substring(0,b).lastIndexOf(" "),m<b+h))if(a=p.substring(m,b+h),p=p.replace(a,""),a=p+q,b=a.match(r))a=
a.substring(b[0].length),b[0].replace(r,g),d=!1;else if(b=a.match(t))a=a.substring(b[0].length),b[0].replace(t,g),d=!1}h=/^<([-a-zA-Z._]*@[-a-zA-Z._]*)()>/;if(b=a.match(h))a=a.substring(b[0].length),b[0].replace(h,g),d=!1}d&&(b=a.indexOf("<"),d=0>b?a:a.substring(0,b),a=0>b?"":a.substring(b),c.chars&&(k.last()&&u[k.last()]&&"textarea"!=k.last()&&"script"!=k.last()&&(b=!1,h=RegExp("\\S\\n","g"),h.test(d)&&(b=!0),h=RegExp("\\n\\S","g"),h.test(d)&&(b=!0),h=RegExp("\\S\\n\\S","g"),h.test(d)&&(b=!0),b?
d=d.replace(/\n/g," "):(h=RegExp("\\n\\n","g"),h.test(d)&&""==d.trim()?d=d.replace(/\n\n/g,""):d==unescape("%20%20")&&(b=new RegExp(unescape("%20"),"g"),d=d.replace(b,"&nbsp;")))),"1"==DEXTTOP.G_CURREDITOR._config.replaceSpace&&e&&(b=new RegExp(unescape("%20%20"),"g"),d=d.replace(b,"&nbsp; ")),c.chars(d)))}if(a==l)throw"Parse Error: "+a;l=a}f()};DEXT5_EDITOR.HTMLParser.HTMLtoXML=function(a,e){var c="",g=DEXTTOP.G_CURREDITOR._config.skipTagInParser;if(""!=g&&0==w){l=l.replace(/,/g,",,");l=","+l+",";
for(var g=g.split(","),f=g.length,b=0;b<f;b++)l=l.replace(","+g[b]+",","");l=l.replace(/,,/g,",");l=l.replace(/^,/g,"");l=l.replace(/,$/g,"");u=n(l);w=!0}DEXT5_EDITOR.HTMLParser(a,e,{start:function(a,b,e){c+="<"+a;for(a=0;a<b.length;a++)c="href"==b[a].name||"src"==b[a].name?c+(" "+b[a].name+"="+b[a].quotationmark+b[a].value+b[a].quotationmark):""!=b[a].quotationmark?c+(" "+b[a].name+"="+b[a].quotationmark+b[a].value+b[a].quotationmark):c+(" "+b[a].name+'="'+b[a].escaped+'"');c+=(e?"/":"")+">"},end:function(a){z[a]||
(c+="</"+a+">")},chars:function(a){c+=a},comment:function(a){c="0"==DEXTTOP.G_CURREDITOR._config.removeComment?c+("\x3c!--"+a+"--\x3e"):c+""}});return c};DEXT5_EDITOR.HTMLParser.RemoveOfficeTag=function(a,e){if(""==a||void 0==a)return"";a=DEXT5_EDITOR.HTMLParser.RemoveOfficeTag2(a);a=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(a);e&&(a=a.replace(/(<span[^>]*>)\s<\/span>/gi,"$1&nbsp;</span>"),a=a.replace(/>\s+</g,"><"));return a};DEXT5_EDITOR.HTMLParser.RemoveOfficeTag2=function(a){var e=RegExp("<o:p></o:p>",
"gi");a=a.replace(e,"");e=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(e,"");e=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(e,"");e=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");a=a.replace(e,"");e=RegExp('<[^>]+(lang=["]?en-us["])[^>]*>',"gi");if(e=a.match(e))for(var c=e.length,g=0;g<c;g++){var f=e[g],b=RegExp('\\slang=[\\"]?en-us[\\"]?',"gi"),f=f.replace(b,"");a=a.replace(e[g],f)}e=RegExp("<[^>]+(mso)[^>]*>","gi");if(e=a.match(e))for(c=e.length,g=0;g<c;g++)f=e[g],"1"==DEXTTOP.G_CURREDITOR._config.removeMsoClass&&
(b=RegExp('\\sclass=[\\"]?(mso)\\w+[\\"]?',"gi"),f=f.replace(b,"")),f=f.replace(/&quot;/gi,"^"),b=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;',"gi"),f=f.replace(b,""),b=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;?',"gi"),f=f.replace(b,""),b=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?'\"\\^@%\\.\\\\_]+; ?","gi"),f=f.replace(b,""),b=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?]+(['\"])","gi"),f=f.replace(b,"$1"),f=f.replace(/\^/gi,"&quot;"),a=a.replace(e[g],f);e=RegExp("<v:shapetype ([^>]+)>[\\s\\S]*?</v:shapetype>",
"gi");a=a.replace(e,"");e=RegExp("<v:shape [^>]+>[\\s\\S]*?(<img [^>]+>)*?</v:shape>","gi");a=a.replace(e,"$1");e=RegExp("<v:shape ([^>]+)>[\\s\\S]*?</v:shape>","gi");a=a.replace(e,"");return a=a.replace(/<\!\[if ppt\]>/gi,"")};DEXT5_EDITOR.HTMLParser.CleanNestedHtml=function(a,e,c,g,f){function b(a,c){for(var d=0,e=a.childNodes.length,f=0;f<e;f++)3!=a.childNodes[f].nodeType&&(c&&(d+=b(a.childNodes[f],c)),d++);return d}function d(a){for(var b="",c=Array(a.childNodes.length),d=0;d<c.length;d++){c[d]=
[];c[d].push(a.childNodes[d]);k(a.childNodes[d],c[d]);var e=d,f=c[d],g=[],h=0;a:for(;h<f.length;h++){for(var l=0;l<g.length;l++)if(g[l]==f[h])continue a;g[g.length]=f[h]}c[e]=g;b+=c[d].join("")}return b}function k(a,b){for(var c=a.childNodes,d=0;d<c.length;d++)b.push(c[d]),c[d].hasChildNodes()&&k(c[d],b);for(var c=0,e;c<b.length;c++){d=b[c];if(1==d.nodeType){e=d.nodeName;if(-1==(" "+p.join(" ").toUpperCase()+" ").search(" "+e.toUpperCase()+" ")){b.splice(c,1);c--;continue}e=d;for(var f="",g=0,h=void 0;g<
e.attributes.length;g++)h=e.attributes[g],1==h.specified&&("style"==h.name?(h=l(e),""!=h&&(f+=' style="'+l(e)+'"')):""!=h.value&&(f+=" "+h.name+'="'+h.value+'"'));e=f;d="<"+d.nodeName.toLowerCase()+e+">"}else 3==d.nodeType&&(d=d.nodeValue.replace(/\n/g,""),d=d.replace(/</g,"&lt;"),d=d.replace(/>/g,"&gt;"));b[c]=d}return b}function l(a){for(var b="",c=0,d=q.length,e;c<d;c++)a.currentStyle?e=a.currentStyle[q[c]]:window.getComputedStyle&&(e=document.defaultView.getComputedStyle(a,null).getPropertyValue(q[c])),
b+=q[c]+":"+e+";";return b}var h=50,q=[],p="p a abbr acronym applet b basefont bdo big br button cite code del dfn em font i iframe img input ins kbd label map object q s samp script select small strike strong sub sup textarea tt u var".split(" ");"undefined"!=typeof c&&(h=parseInt(c));c="p";g&&(c=g);g=a._DOC;f&&(g=f);var m=g.getElementsByTagName(c);f=!1;c=0;for(var n=m.length;c<n;c++)if(b(m[c],!0)>h){f=!0;break}if(f)if(g)try{c=0;for(var n=m.length,r;c<n;c++)b(m[c],!0)>h&&(r=d(m[c]),r=DEXT5_EDITOR.HTMLParser.HTMLtoXML(r),
m[c].innerHTML=r);return g.innerHTML}catch(t){}else showProcessingBackground(),setTimeout(function(){a._BODY.contentEditable=!1;try{if("2"==e)DEXTTOP.DEXT5.DextCommands("select_all",a.ID),DEXTTOP.DEXT5.DextCommands("remove_css",a.ID),DEXTTOP.DEXT5.DextCommands("remove_format",a.ID),a._FRAMEWIN.setFocusToBody(),setTimeout(function(){a._FRAMEWIN.doSetCaretPosition(a._BODY.firstChild,0)},20);else for(var c=0,f=m.length,g;c<f;c++)b(m[c],!0)>h&&(g=d(m[c]),g=DEXT5_EDITOR.HTMLParser.HTMLtoXML(g),m[c].innerHTML=
g)}catch(k){}hideProcessingBackground();a._BODY.contentEditable=!0},G_Progress_LoadTime)};DEXT5_EDITOR.HTMLParser.makeMap=function(a){return n(a)}})();
