ALTER TABLE COMTNAUTHORROLERELATE 
DROP CONSTRAINT COMTNAUTHORROLERELATE_FK1;

ALTER TABLE COMTNAUTHORROLERELATE 
DROP CONSTRAINT COMTNAUTHORROLERELATE_FK2;

/*직원 테이블 생성 스크립트*/
CREATE TABLE EF_EMP 
(
  EMP_NO VARCHAR2(20) NOT NULL 
, EMP_NM VARCHAR2(50) NOT NULL 
, DEPT_CD VARCHAR2(20) 
, DEPT_NM VARCHAR2(100) 
, EMAIL VARCHAR2(50) 
, TEL VARCHAR2(20) 
, FAX VARCHAR2(20) 
, JOB VARCHAR2(40) 
, DUTY VARCHAR2(40) 
, BIZ_CD VARCHAR2(20) 
, EMP_TYPE VARCHAR2(5) 
, PASSWORD VARCHAR2(200) NOT NULL 
, PWD_FAIL_CNT NUMBER 
, LAST_PWD_CHG_DT DATE 
, LAST_LOGIN_DT DATE 
, USE_YN VARCHAR2(1) 
, RETIRE_YN VARCHAR2(1) 
, STATUS VARCHAR2(3) 
, FRST_REGISTER_ID VARCHAR2(20) 
, LAST_UPDUSR_ID VARCHAR2(20) 
, FRST_REGIST_PNTTM DATE 
, LAST_UPDT_PNTTM DATE 
, CONSTRAINT EF_EMP_PK PRIMARY KEY 
  (
    EMP_NO 
  )
  ENABLE 
);

COMMENT ON COLUMN EF_EMP.EMP_NM IS '이름';
COMMENT ON COLUMN EF_EMP.DEPT_CD IS '부서코드';
COMMENT ON COLUMN EF_EMP.DEPT_NM IS '부서명';
COMMENT ON COLUMN EF_EMP.EMAIL IS '이메일';
COMMENT ON COLUMN EF_EMP.TEL IS '전화번호';
COMMENT ON COLUMN EF_EMP.FAX IS '팩스';
COMMENT ON COLUMN EF_EMP.JOB IS '직위';
COMMENT ON COLUMN EF_EMP.DUTY IS '직책';
COMMENT ON COLUMN EF_EMP.BIZ_CD IS '회사코드';
COMMENT ON COLUMN EF_EMP.EMP_TYPE IS '사용자 타입';
COMMENT ON COLUMN EF_EMP.PASSWORD IS '비밀번호';
COMMENT ON COLUMN EF_EMP.PWD_FAIL_CNT IS '비밀번호 실패 횟수';
COMMENT ON COLUMN EF_EMP.LAST_PWD_CHG_DT IS '최종 패스워드 변경 일시';
COMMENT ON COLUMN EF_EMP.LAST_LOGIN_DT IS '최종 로그인 일시';
COMMENT ON COLUMN EF_EMP.USE_YN IS '사용 유무';
COMMENT ON COLUMN EF_EMP.RETIRE_YN IS '퇴사 유무';
COMMENT ON COLUMN EF_EMP.STATUS IS '상태';
COMMENT ON COLUMN EF_EMP.FRST_REGISTER_ID IS '최초 등록자';
COMMENT ON COLUMN EF_EMP.LAST_UPDUSR_ID IS '최종 수정자';
COMMENT ON COLUMN EF_EMP.FRST_REGIST_PNTTM IS '최초 등록일';
COMMENT ON COLUMN EF_EMP.LAST_UPDT_PNTTM IS '최종 수정일시';


/*협력사 테이블 생성 스크립트*/
CREATE TABLE EF_VENDOR 
(
  VENDOR_CD VARCHAR2(20) NOT NULL 
, VENDOR_NM VARCHAR2(100) NOT NULL 
, VENDOR_BIZ_NO VARCHAR2(10) 
, VENDOR_REPRE_NM VARCHAR2(100) 
, VENDOR_TYPE VARCHAR2(5) NOT NULL 
, BIZ_CLASS VARCHAR2(200) 
, BIZ_TYPE VARCHAR2(200) 
, ADDR VARCHAR2(400) 
, FAX VARCHAR2(20) 
, TEL VARCHAR2(20) 
, EMAIL VARCHAR2(50) 
, USE_YN VARCHAR2(1) 
, STATUS VARCHAR2(3) 
, FRST_REGISTER_ID VARCHAR2(20) 
, LAST_UPDUSR_ID VARCHAR2(20) 
, FRST_REGIST_PNTTM DATE 
, LAST_UPDT_PNTTM DATE 
, CONSTRAINT EF_VENDOR_PK PRIMARY KEY 
  (
    VENDOR_CD 
  )
  ENABLE 
);

COMMENT ON COLUMN EF_VENDOR.VENDOR_CD IS '협력사 코드';
COMMENT ON COLUMN EF_VENDOR.VENDOR_NM IS '협력사명';
COMMENT ON COLUMN EF_VENDOR.VENDOR_BIZ_NO IS '협력사 사업자번호';
COMMENT ON COLUMN EF_VENDOR.VENDOR_REPRE_NM IS '대표자명';
COMMENT ON COLUMN EF_VENDOR.VENDOR_TYPE IS '협력사 타입';
COMMENT ON COLUMN EF_VENDOR.BIZ_CLASS IS '업종';
COMMENT ON COLUMN EF_VENDOR.BIZ_TYPE IS '업태';
COMMENT ON COLUMN EF_VENDOR.ADDR IS '주소';
COMMENT ON COLUMN EF_VENDOR.FAX IS '대표 팩스';
COMMENT ON COLUMN EF_VENDOR.TEL IS '대표 전화번호';
COMMENT ON COLUMN EF_VENDOR.EMAIL IS '대표 이메일';
COMMENT ON COLUMN EF_VENDOR.USE_YN IS '사용유무';
COMMENT ON COLUMN EF_VENDOR.STATUS IS '상태';
COMMENT ON COLUMN EF_VENDOR.FRST_REGISTER_ID IS '최초 등록자';
COMMENT ON COLUMN EF_VENDOR.LAST_UPDUSR_ID IS '최종 수정자';
COMMENT ON COLUMN EF_VENDOR.FRST_REGIST_PNTTM IS '최초 등록일';
COMMENT ON COLUMN EF_VENDOR.LAST_UPDT_PNTTM IS '최종 수정일';

/*협력사 사용자 테이블 생성 스크립트*/
CREATE TABLE EF_VENDOR_USER 
(
  USER_ID VARCHAR2(20) NOT NULL
, USER_NM VARCHAR2(50) NOT NULL 
, VENDOR_CD VARCHAR2(20)
, DEPT_NM VARCHAR2(100) 
, MOBILE VARCHAR2(20) 
, EMAIL VARCHAR2(50) 
, TEL VARCHAR2(20) 
, FAX VARCHAR2(20) 
, JOB VARCHAR2(40) 
, DUTY VARCHAR2(40) 
, ADM_USER_YN VARCHAR2(1) 
, PASSWORD VARCHAR2(200) NOT NULL 
, PWD_FAIL_CNT NUMBER 
, LAST_PWD_CHG_DT DATE 
, LAST_LOGIN_DT DATE 
, USE_YN VARCHAR2(1) 
, STATUS VARCHAR2(3) 
, FRST_REGISTER_ID VARCHAR2(20) 
, LAST_UPDUSR_ID VARCHAR2(20) 
, FRST_REGIST_PNTTM DATE 
, LAST_UPDT_PNTTM DATE 
, CONSTRAINT EF_VENDOR_USER_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

COMMENT ON COLUMN EF_VENDOR_USER.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN EF_VENDOR_USER.USER_NM IS '사명자명';
COMMENT ON COLUMN EF_VENDOR_USER.VENDOR_CD IS '협력사코드';
COMMENT ON COLUMN EF_VENDOR_USER.DEPT_NM IS '부서명';
COMMENT ON COLUMN EF_VENDOR_USER.MOBILE IS '핸드폰번호';
COMMENT ON COLUMN EF_VENDOR_USER.EMAIL IS '이메일';
COMMENT ON COLUMN EF_VENDOR_USER.TEL IS '전화번호';
COMMENT ON COLUMN EF_VENDOR_USER.FAX IS '팩스';
COMMENT ON COLUMN EF_VENDOR_USER.JOB IS '직위';
COMMENT ON COLUMN EF_VENDOR_USER.DUTY IS '직책';
COMMENT ON COLUMN EF_VENDOR_USER.ADM_USER_YN IS '대표관리자 여부';
COMMENT ON COLUMN EF_VENDOR_USER.PASSWORD IS '패스워드';
COMMENT ON COLUMN EF_VENDOR_USER.PWD_FAIL_CNT IS '패스워드 실패 횟수';
COMMENT ON COLUMN EF_VENDOR_USER.LAST_PWD_CHG_DT IS '패스워드 최종 변경 일시';
COMMENT ON COLUMN EF_VENDOR_USER.LAST_LOGIN_DT IS '최종 로그인 일시';
COMMENT ON COLUMN EF_VENDOR_USER.USE_YN IS '사용유무';
COMMENT ON COLUMN EF_VENDOR_USER.STATUS IS '상태';
COMMENT ON COLUMN EF_VENDOR_USER.FRST_REGISTER_ID IS '최초 등록자';
COMMENT ON COLUMN EF_VENDOR_USER.LAST_UPDUSR_ID IS '최종 수정자';
COMMENT ON COLUMN EF_VENDOR_USER.FRST_REGIST_PNTTM IS '최초 등록일';
COMMENT ON COLUMN EF_VENDOR_USER.LAST_UPDT_PNTTM IS '최종 수정일';

/*메뉴관리 테이블 URL 필드 추가*/
ALTER TABLE COMTNMENUINFO 
ADD (URL VARCHAR2(250) );

/*추가된 URL 필드에 기존 프로그램 관리 테이블 URL 마이그레이션 처리*/
UPDATE COMTNMENUINFO A 
SET URL = (SELECT URL FROM COMTNPROGRMLIST WHERE PROGRM_FILE_NM = A.PROGRM_FILE_NM)
WHERE URL IS NULL;

ALTER TABLE COMTNMENUINFO 
MODIFY CONSTRAINT COMTNMENUINFO_FK2 DISABLE;

/*Console 사용자 테이블 생성 스크립트*/
CREATE TABLE EA_USER 
(
  USER_ID VARCHAR2(20) NOT NULL
, USER_NM VARCHAR2(50) NOT NULL 
, DEPT_NM VARCHAR2(100) 
, MOBILE VARCHAR2(20) 
, EMAIL VARCHAR2(50) 
, TEL VARCHAR2(20) 
, PASSWORD VARCHAR2(200) NOT NULL 
, PWD_FAIL_CNT NUMBER 
, LAST_PWD_CHG_DT DATE 
, LAST_LOGIN_DT DATE 
, USE_YN VARCHAR2(1) 
, FRST_REGISTER_ID VARCHAR2(20) 
, LAST_UPDUSR_ID VARCHAR2(20) 
, FRST_REGIST_PNTTM DATE 
, LAST_UPDT_PNTTM DATE 
, CONSTRAINT EA_USER_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

COMMENT ON COLUMN EA_USER.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN EA_USER.USER_NM IS '사명자명';
COMMENT ON COLUMN EA_USER.DEPT_NM IS '부서명';
COMMENT ON COLUMN EA_USER.MOBILE IS '핸드폰번호';
COMMENT ON COLUMN EA_USER.EMAIL IS '이메일';
COMMENT ON COLUMN EA_USER.TEL IS '전화번호';
COMMENT ON COLUMN EA_USER.PASSWORD IS '패스워드';
COMMENT ON COLUMN EA_USER.PWD_FAIL_CNT IS '패스워드 실패 횟수';
COMMENT ON COLUMN EA_USER.LAST_PWD_CHG_DT IS '패스워드 최종 변경 일시';
COMMENT ON COLUMN EA_USER.LAST_LOGIN_DT IS '최종 로그인 일시';
COMMENT ON COLUMN EA_USER.USE_YN IS '사용유무';
COMMENT ON COLUMN EA_USER.FRST_REGISTER_ID IS '최초 등록자';
COMMENT ON COLUMN EA_USER.LAST_UPDUSR_ID IS '최종 수정자';
COMMENT ON COLUMN EA_USER.FRST_REGIST_PNTTM IS '최초 등록일';
COMMENT ON COLUMN EA_USER.LAST_UPDT_PNTTM IS '최종 수정일';